sudo: required
services:
  - docker

before_install:
  - docker build -t 12122323/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run 12122323/react-test npm test -- --coverage

/*
after_success:
 - docker build -t 12122323/multi-client ./client
 - docker build -t 12122323/multi-nginx ./nginx
 - docker build -t 12122323/multi-server ./server
 - docker build -t 12122323/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push 12122323/multi-client
 - docker push 12122323/multi-nginx
 - docker push 12122323/multi-server 
 - docker push 12122323/multi-worker
*/

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-111343287320"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
